# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failue: always
  slack: cir-kit:ScokSrDzpegEnxbcXuxmWAhz
env:
  matrix:
    - ROS_DISTRO=indigo ROS_REPO=ros              UPSTREAM_WORKSPACE=cirkit_unit03_apps_travis.rosinstall BEFORE_SCRIPT="yes | sudo apt-add-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl; sudo apt-get update -qq; sudo apt-get install -y libpcl-all;"
    - ROS_DISTRO=indigo ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=cirkit_unit03_apps_travis.rosinstall BEFORE_SCRIPT="yes | sudo apt-add-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl; sudo apt-get update -qq; sudo apt-get install -y libpcl-all;"
    - ROS_DISTRO=indigo TEST=clang-format         UPSTREAM_WORKSPACE=cirkit_unit03_apps_travis.rosinstall
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
